name: Upstream Kernel

on:
  push:
    branches:
      - main

jobs:
  upstream_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.name "maxregnerisch"
          git config --global user.email "plosmrasif@gmail.com"

      - name: Upstream Kernel
        run: |
          git remote add upstream https://github.com/torvalds/linux.git
          git fetch upstream --tags
          git checkout -b upstream-5.4 upstream/v5.4
          git merge --no-commit --no-ff main
          # Resolve any conflicts and make necessary changes
          git commit -m "Upstream kernel from 4.14.194 to 5.4"
          git push origin upstream-5.4

      - name: Update Base Repository
        run: |
          git remote add base https://github.com/maxregnerisch/android_kernel_samsung_exynos9610_mint.git
          git fetch base
          git checkout wip-12.5.1_rel
          git merge --no-commit --no-ff base/wip-12.5.1_rel
          # Resolve any conflicts and make necessary changes
          git commit -m "Merge base repository changes"
          git push origin wip-12.5.1_rel
